### ISSUE TITLE
Invalid code generated when input structure is used as regular function parameter

### ISSUE THREAD

**Issue by Hyp-X** [LukasBanana/XShaderCompiler#6]
Paste the following shader into xsc_debugger:

struct VSIN
{
    float3 position : POSITION;
};

float3 GetPosition(VSIN i)
{
    return i.position;
}

float4 VSMain(VSIN i) : SV_Position
{
    return float4(GetPosition(i), 1);
}

and set the entry point to VSMain.

This will generate the following shader:

// GLSL Vertex Shader "VSMain"
// Generated by XShaderCompiler
// 10/01/2017 20:33:34

#version 130

in vec3 position;

vec3 GetPosition(VSIN i)
{
    return position;
}

void main()
{
    gl_Position = vec4(GetPosition(i), 1);
}

This will obviously not compile.
I tried this because I run into a similar issue when trying to make geometry shaders to work.
The reason I write this as an issue is because I don't know how you want to handle it.

Solution 1: Fall back to what other compilers do and keep the structure:

#version 130

in vec3 position;

struct VSIN
{
    vec3 position;
};

vec3 GetPosition(VSIN i)
{
    return i.position;
}

void main()
{
    VSIN x;
    x.position = position;
    gl_Position = vec4(GetPosition(x), 1);
}

Solution 2: Propagate the input access to other functions and kill the parameter

#version 130

in vec3 position;

vec3 GetPosition()
{
    return position;
}

void main()
{
    gl_Position = vec4(GetPosition(), 1);
}

The second solution looks nicer but it needs to remove the parameter of GetPosition()
In case of geometry shaders it is possible to call a function with an array element (the data of just one vertex) in which case the parameter would need to be replaced with just the array index.

**Comment by LukasBanana** [comment]
I think I will handle this with the ReferenceAnalyzer, which must detect if the struct is used by another function than the main entry point.

This issue is some sort of a relict from the fashion I handled the I/O semantics, when I always used input/output blocks.
Back then the struct was translated into a shader block instead of a struct.
But now the compiler always translates I/O semantics into global in/out members.

I try to find a little time tomorrow to fix this.

**EDIT:**
I think your 2nd proposal is the better solution.
Killing the parameter and propagate the global input/output members.
It might be more complicated, but that's actually what I currently do with the main entry point.

**Comment by LukasBanana** [comment]
It's still incomplete, but the code you posted should be translated correctly now.
The I/O semantic differences between HLSL and GLSL seems to most complex :-/

**Comment by LukasBanana** [comment]
This issue should be solved now, at least for Vertex-, Fragment-, and Compute shaders.
Geometry and Tessellation shaders are still incomplete.
