### ISSUE TITLE
UAV register mapping, and MIX issue 

### ISSUE THREAD

**Issue by ghost** [LukasBanana/XShaderCompiler#63]
Hello. Why does XShaderCompiler not remap DX registers to GL automatically? For example, "u6" as "binding = 6"? I think it will simpler than write hand-write maps. 

Also, I merge to issues `mix` operation issue from GLSL450. 
```
ivec2 leftright = mix(ivec2(-1, -1), node.pdata.xy, ivec2(overlaps));
```

Booleans should not to conversion, even if HLSL said "lerp".

**Comment by LukasBanana** [comment]
Have you tried the `-EB` option for **E**xplicit **B**inding?
And please open one ticket for every issue, so it's easier to reply to them.

**Comment by ghost** [comment]
Yes, I tried, but with auto-bind conflicts as I seen. 
What about `mix` issue, that outputs with ternary and `lerp`? (also, available from GLSL450 with ints and bools)

**Comment by LukasBanana** [comment]
`-AB` will of course override all our regsiters, because it automatically generates all binding slots.
However, if you use `-EB` only (e.g. `xsc -EB on -AB off`) the compiler preserves all your binding slots.

About your `mix` issue, this is indeed a problem the compiler is currently facing.
I guess this belongs to the part where the compiler determines the argument types of the intrinsics which is a generic approach instead of enumerating all overloaded intrinsic variants.
I'll put it on the TODO list, but I assume the type-cast should work in principle, although it is not very pretty.

**Comment by LukasBanana** [comment]
@capitalknew did the ~~`-AB`~~ (**EDIT**: I meant `-EB`) option work for you?

**Comment by ghost** [comment]
Worked, but did just by ordering (who first, so given register). I used -EB.

**Comment by LukasBanana** [comment]
Is this still an open issue? I think the major problem was solved.
If you still encouter an issue with the `mix` intrinsic, open a new ticket just for that.
