### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by v7medz** [LukasBanana/XShaderCompiler#76]
Hey, first thanks to the creators of this library, I am using the library in my game engine and noticed some bugs:
- When enabling separate shaders option in GLSL 330, with allow extensions 'on', XSC doesn't include 
`#extension GL_ARB_separate_shader_objects : enable` in the generated code.
- Auto binding has many bugs
  - Auto binding takes sampler states into count "when it actually shouldn't" 
         Example HLSL:
         `Texture2D NE_Tex_Diffuse1 : register(t0);`
         `SamplerState NE_Diffuse1_Sampler : register(s0);`
         `Texture2D NE_Tex_Specular1 : register(t1);`
         `SamplerState NE_Specular1_Sampler : register(s1);`
         Generated GLSL
         `layout(binding = 0) uniform sampler2D NE_Tex_Diffuse1;`
         `layout(binding = 2) uniform sampler2D NE_Tex_Specular1; //Should be one`
  - Auto binding doesn't generate binding locations according to DirectX 'register'
         Example HLSL:
         `Texture2D NE_Tex_Diffuse1 : register(t7);`
         `Texture2D NE_Tex_Specular1 : register(t3);`
         Generated GLSL
         `layout(binding = 0) uniform sampler2D NE_Tex_Diffuse1;  //Should be seven`
         `layout(binding = 1) uniform sampler2D NE_Tex_Specular1; //Should be three`

Also a question, Is the library still supported by the creators?
Thanks.

**Comment by v7medz** [comment]
Also Reflection data seems too limited, for example textures reflection only return name and location, but not its type, and constant buffer (UBO) reflections only contain name and location but no data about its variables or size...

Note: I know that these data can be queried with opengl in runtime, but it would be nicer and cleaner if XSC expose them to user..

**Comment by LukasBanana** [comment]
**Extension:**
Yes, that seems to be a bug. Do you now which GLSL version this extension requires?
It's always awkward to search for exact GLSL versions of Shader Extensions for GL.

**Auto Binding:**
Auto binding generates binding slots **auto**matically (as stated [here](https://github.com/LukasBanana/XShaderCompiler/blob/master/inc/Xsc/Xsc.h#L149)) in a sequential fashion. If you want your own specified register slots, use [`explicitBinding`](https://github.com/LukasBanana/XShaderCompiler/blob/master/inc/Xsc/Xsc.h#L157).

You may also have already noticed, that GLSL does not allow separation of samplers and textures (except for Vulkan), which leads to some issues when translating HLSL to GLSL.
So Xsc always uses the _Textures_ as output, not the _Samplers_. However, it looks like you already took this into account.
Nevertheless, I don't see why Xsc generates your first example to binding slots 0 and 2 (instead of 0 and 1).
Can you show a little more of your shader?

**Shader Reflection:**
That could indeed be extended. For now, you have to use the OpenGL/ Direct3D API for detailed reflection, but I'll put your request on the [TODO](https://github.com/LukasBanana/XShaderCompiler/blob/master/TODO.md#requested-features) list for _Requested Features_.

BTW: When you have multiple issues to report, feel free to create multiple tickets, since that makes it easier to manage them.

Kind regards,
Lukas

**Comment by LukasBanana** [comment]
About your reflection requests: some forks of this repository already added some details to the shader reflections: [commit 9b0b6fe](https://github.com/Gabriele91/XShaderCompiler/commit/9b0b6feaee47c67288e5ce94beb8128f886814f5) (by @Gabriele91)

**Comment by v7medz** [comment]
Extension: https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_separate_shader_objects.txt 
GLSL 410, OpenGL 4.1

I am going to fork the project, and apply some modifications to it to separate certain things as auto binding overrides explicit binding...

**Comment by LukasBanana** [comment]
If there are still issues on this, just re-open the ticket.
