### ISSUE TITLE
EmitVertex() should have no parameters

### ISSUE THREAD

**Issue by Hyp-X** [LukasBanana/XShaderCompiler#8]
If you compile the following GS shader:

struct GSOUT
{
    float3 Position : POSITION;
};

[maxvertexcount(2)]
void GSMain(line float3 i[2] : POSITION, inout LineStream<GSOUT> stream)
{
	GSOUT p;
	p.Position = i[0];
	stream.Append(p);
	p.Position = i[1];
	stream.Append(p);
}

It outputs:

#version 150

in vec3 xsc_vary_POSITION;

struct GSOUT
{
    vec3 Position;
};

void main()
{
    GSOUT p;
    p.Position = xsc_vary_POSITION[0];
    EmitVertex(p);
    p.Position = xsc_vary_POSITION[1];
    EmitVertex(p);
}

EmitVertex() has no input parameters so it should be translated without them.

I think the only way to handle this one is the not-so-nice way:

#version 150

in vec3 xsc_vary_POSITION;

struct GSOUT
{
    vec3 Position;
};

void main()
{
    GSOUT p;
    p.Position = xsc_vary_POSITION[0];
    gl_Position = p.Position;
    EmitVertex();
    p.Position = xsc_vary_POSITION[1];
    gl_Position = p.Position;
    EmitVertex();
}

The nice way would be...

in vec3 xsc_vary_POSITION;

void main()
{
    gl_Position = xsc_vary_POSITION[0];
    EmitVertex();
    gl_Position = xsc_vary_POSITION[1];
    EmitVertex();
}

...but that's very hard to do in the generic case. (Writing to GSOUT might be in a function and might not occur in this order)

**Comment by LukasBanana** [comment]
I'm aware of this issue, and I think this will take a little more investigation.
Anway, I'll keep your issue open until it's done.

The output code should look something like this:
```
layout(lines) in;
layout(line_strip​, max_vertices = 2) out;

in vec3 xsc_vary_POSITION[];
out vec3 xsc_vary_OTHERPOSITION;

void main()
{
    xsc_vary_OTHERPOSITION = xsc_vary_POSITION[0];
    EmitVertex();
    xsc_vary_OTHERPOSITION = xsc_vary_POSITION[1];
    EmitVertex();
}
```
There's another problem: the semantic "POSITION" is used twice: as input _and_ output.
This is not a problem when only a vertex and fragment shader is used, since the vertex input members are named differently.
But for the geometry shader the naming convention for input and output semantics is equal.
Now if we change the output or input namings for geometry shaders (e.g. "xsc_geom_" prefix, instead of "xsc_vary_"), we also have to change this for the counterpart in the other shader stages.
But that will lead to new problems, since the shader stages are cross-compiled independently.

So you see, for geometry shader support there's a lot more to do ;-)
But I think this is something which should be just declared as an official "limitation",
i.e. the programmer should be aware of this limitation, and should never use the same semantic
as input and output in the same shader stage.

**Comment by Hyp-X** [comment]
You just made me realize that in HLSL I can even reuse the entire structure:

struct VSOUT
{
    float3 Position : POSITION;
};

[maxvertexcount(2)]
void GSMain(line VSOUT i[2], inout LineStream<VSOUT> stream)
{
	VSOUT p;
	p.Position = i[0].Position;
	stream.Append(p);
	p.Position = i[1].Position;
	stream.Append(p);
}

This compiles with fxc.
I don't mind if something like won't translate into GLSL - it has no practical use anyway.

**Comment by LukasBanana** [comment]
The arguments from `EmitVertex` function calls are now removed by the `GLSLConverter` class.

There's more work to do for this inside the `HLSLAnalyzer`, when a non-struct object is passed as argument to the `Append` intrinsic for instance.

Example:
```
stream.Append((GSOUT)i[0].Position);
stream.Append((GSOUT)i[1].Position);
```
This currently translates to:
```
EmitVertex();
EmitVertex();
```
But that's another issue.
