### ISSUE TITLE
Context error with different function signature

### ISSUE THREAD

**Issue by moradin** [LukasBanana/XShaderCompiler#91]
I'm getting the following error with the code below.

context error (mtx.hlsl:44:12) : identifier 'Mul42' already declared in this scope; previous declaration at (mtx.hlsl:36:12)

```
    float2 Mul42(float4 v_vec, float4 v_mtx[2])
    {
        ...
    }

    float2 Mul42(float4 v_vec, float4 v_mtx[4])
    {
        ...
    }
```

I tried every other option on Shader Playground and they all worked with this code.

**Comment by LukasBanana** [comment]
That's a bug indeed. Thanks for the report. I'll take care of it.

**Comment by moradin** [comment]
sorry that was an accidental click

**Comment by LukasBanana** [comment]
Should be fixed with [5e1c75b](https://github.com/LukasBanana/XShaderCompiler/commit/5e1c75b9dd804cb90d97babcc0ce8e3f7694335f).

I also refactored the output of default arguments: the result of a default argument expression is no written directly to the output:
```hlsl
void foo(int x = 2*3.4);
```
Translation:
```glsl
// Before:
foo(2*3.4);

// After:
foo(6.8);
```
The compiler now also reports an error when a non-constant expression is declared as a default argument.

**Comment by moradin** [comment]
Sounds great! I don't know if I will have time to check it today but I hope I will

**Comment by LukasBanana** [comment]
With the changes of the `Variant` class, a bug has moved in which I now kicked out again in [0c01e12](https://github.com/LukasBanana/XShaderCompiler/commit/0c01e12082e5dcfa92737aa3a29cc7758dc574cb).

**Comment by moradin** [comment]
I can confirm that this resolved the issue I had.
